SMS = {}

function SMS:New(name)
    self[name] = Ext.Net.CreateChannel(ModuleUUID, name)
end

SMS:New("FetchEquipment")
SMS:New("FetchNPCs")
SMS:New("SendEquipment")
SMS:New("SendNPCs")
SMS:New("SpawnTemplate")
SMS:New("SpawnAllEquipment")
SMS:New("SpawnCharacter")
SMS:New("DespawnCharacter")
SMS:New("ManageNPC")
SMS:New("FetchSpells")
SMS:New("ManageSpells")
SMS:New("SendSpells")
SMS:New("LearnSpell")
SMS:New("SendConsumables")
SMS:New("FetchConsumables")
SMS:New("SendWaypoints")
SMS:New("FetchWaypoints")
SMS:New("TeleportToWaypoint")
SMS:New("RecruitCompanion")
SMS:New("CompanionApproval")
SMS:New("FetchPassives")
SMS:New("SendPassives")
SMS:New("AddPassive")
SMS:New("AddPassiveOnItem")
SMS:New("RemovePassiveFromItem")
SMS:New("FetchStatuses")
SMS:New("SendStatuses")
SMS:New("ApplyStatus")
SMS:New("ApplyStatusToItem")
SMS:New("RemoveStatusFromItem")
SMS:New("FetchTags")
SMS:New("SendTags")
SMS:New("ManageTag")
SMS:New("AddGold")
SMS:New("AddExperience")
SMS:New("AddTadpoles")
SMS:New("AddInspiration")
SMS:New("RestoreParty")
SMS:New("ResetCooldowns")
SMS:New("StartRespec")
SMS:New("StartChangeAppearance")
SMS:New("FetchPartyMembers")
SMS:New("SendPartyMembers")
SMS:New("FetchModifiedItemsData")
SMS:New("SendModifiedItemsData")